name: Check and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_and_publish:
    name: Check and publish product
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check code quality
      id: check
      uses: jmorenoamor/api-connect-code-quality-action@master
      with:
        product: product/sandbox.yaml
        rules: quality_rules.yaml

    - name: Notify
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,workflow,action,commit
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
